[package]
name = "pycrucible"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.4"
maplit = "1.0"
lazy_static = "1.4"
once_cell = "1.18"
clap = { version = "4.2", features = ["derive"] }
spinners = "4"
zip = "2.5"
