name: Supported use. Build and run an example app with PyCrucible

on:
  push:
    branches:
      [CI_Cowsay_Example,]
  workflow_dispatch:


jobs:
  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable


      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: Swatinem/rust-cache@v2

      - name: Compile release build
        run: cargo build --release

      - name: Copy PyCrucible to project
        shell: bash
        run: cp ./target/release/pycrucible.exe my_cowsay

      - name: Run PyCrucible
        shell: bash
        working-directory: my_cowsay
        run: ./pycrucible.exe -e ${GITHUB_WORKSPACE}/my_cowsay -o cowsay.exe

      - name: Test cowsay.exe
        shell: bash
        working-directory: my_cowsay
        run: ./cowsay.exe  


  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable


      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: Swatinem/rust-cache@v2

      - name: Compile release build
        run: cargo build --release


      - name: Copy PyCrucible to project
        shell: bash
        run: cp ./target/release/pycrucible my_cowsay

      - name: Run PyCrucible
        shell: bash
        working-directory: my_cowsay
        run: ./pycrucible -e . -o cowsay


      - name: Test cowsay
        shell: bash
        working-directory: my_cowsay
        run: ./cowsay 


          
      