name: Supported use. Build and run an example app with PyCrucible

on:
  push:
    branches:
      [External_example_repo,]
  workflow_dispatch:


jobs:
  build_and_embed_example:
    name: Build and Embed example project
    strategy:
      matrix:
        config:
          [ {runner: windows-latest,
             shell: cmd,
             bin_ext: .exe,
            },
            {runner: ubuntu-24.04,
             shell: bash,
             bin_ext: "",
            },
          ]   
          
    runs-on: ${{ matrix.config.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable


      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: Swatinem/rust-cache@v2

      - name: Compile release build
        run: cargo build --release

      - name: Clone example project
        run: git clone https://github.com/JamesParrott/simple-python-project-for-PyCrucible/

      - name: Copy PyCrucible to project
        shell: bash
        run: cp ./target/release/pycrucible${{ matrix.config.bin_ext}} simple-python-project-for-PyCrucible

      - name: Run PyCrucible
        if: ${{ matrix.config.runner == 'windows-latest' }}
        shell: ${{ matrix.config.shell }}
        working-directory: simple-python-project-for-PyCrucible
        run: ./pycrucible.exe -e ${GITHUB_WORKSPACE}/simple-python-project-for-PyCrucible -o cowsay.exe

      - name: Run PyCrucible
        if: ${{ matrix.config.runner != 'windows-latest' }}
        working-directory: simple-python-project-for-PyCrucible
        run: ./pycrucible -e . -o cowsay

      - name: Test cowsay${{ matrix.config.bin_ext}}
        shell: bash
        working-directory: simple-python-project-for-PyCrucible
        run: ./cowsay${{ matrix.config.bin_ext}}  

      # Workaround / hack ?
      # - name: Copy main.py to payload
      #   shell: bash
      #   working-directory: simple-python-project-for-PyCrucible
      #   run: cp main.py payload

      # - name: Test cowsay executable
      #   shell: bash
      #   working-directory: simple-python-project-for-PyCrucible
      #   run: ./cowsay${{ matrix.config.bin_ext}} 